### ISSUE TITLE
Reconsider "baseline" repo name

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-prototype-kit#1]
Let's figure a better name for this repo. I'm thinking more specific, like `fsa-prototype-kit`. What best describes what this is used for?

**Comment by bignamehere** [comment]
I am agreeable with updating the name. I wasn't sure if we planned on keeping this repo or folding it into FSA Style as a branch, but I wanted to keep it separate just in case we wanted it to remain it's own project.

The intent of this project is to have a "baseline" starting point, from a tooling perspective, that allows designers and devs to create a new project and utilize FSA Style (within node_modules). Any name that clearly represents that idea, I am fine with. "fsa-prototype-kit" seems reasonable.

**Comment by bignamehere** [comment]
renamed and closing
