### ISSUE TITLE
Partial file HTML comment 

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-prototype-kit#7]
More of a want than a need, so can consider as a very nice-to-have.

### Ask

Would like to Inspect the HTML source and see HTML comments of partial beginng/end.

### Example

With the current Webpack/HBS setup, it takes from `src`...

```hbs
<div class="foo">
  {{> ../components/fsa-field }}
</div>
```
...and compiles to `dist` as...
```html
<div class="foo">
  <div class="fsa-field">...</div>
</div>
```
It'd be super cool if it could render as...
```html
<div class="foo">
  <!-- [ START ] src/components/fsa-field -->
  <div class="fsa-field">...</div>
  <!-- [  END  ] src/components/fsa-field -->
</div>
```
Bonus points for retaining any parameters, e.g.
```html
<div class="foo">
  <!-- [ START ] src/components/fsa-field ID="blah-0003" LABEL="Name" REQUIRED="true -->
  <div class="fsa-field">...</div>
  <!-- [  END  ] src/components/fsa-field ID="blah-0003" LABEL="Name" REQUIRED="true -->
</div>
```
### Background
I utilized this in the PCP prototype, though I had to hack the `grunt-simple-include` package to do so ([screenshot](https://user-images.githubusercontent.com/1165933/44530410-e704ac00-a6b3-11e8-87ba-57cf7fd7d1e4.png)). For an example [inspect a PCP-II prototype page](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/workflow_discovery.html).

**Comment by bignamehere** [comment]
The addition of Handlebars has enabled this functionality. This commit includes feature... 882108d
